CREATE TABLE Allomas(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1),
    nev VARCHAR2(50) NOT NULL,
    szelesseg BINARY_FLOAT,
    hosszusag BINARY_FLOAT,
    PRIMARY KEY(id)
);

CREATE TABLE Jarat(
    jaratszam NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1),
    uthossz NUMBER(5),
    indulasi_ido DATE,
    indulasi_hely NUMBER NOT NULL,
    erkezesi_ido DATE,
    erkezesi_hely NUMBER NOT NULL,
    PRIMARY KEY(jaratszam),
    FOREIGN KEY(indulasi_hely) REFERENCES Allomas(id),
    FOREIGN KEY(erkezesi_hely) REFERENCES Allomas(id)
);

CREATE TABLE Atszallas(
    ido DATE,
    hely NUMBER NOT NULL,
    jaratszam NUMBER NOT NULL,
    FOREIGN KEY(hely) REFERENCES Allomas(id),
    FOREIGN KEY(jaratszam) REFERENCES Jarat(jaratszam)
);

CREATE TABLE Arkategoria(
    ar NUMBER(5) NOT NULL,
    cimke VARCHAR2(50) NOT NULL,
    jaratszam NUMBER NOT NULL,
    PRIMARY KEY(jaratszam, cimke),
    FOREIGN KEY(jaratszam) REFERENCES Jarat(jaratszam)
);

CREATE TABLE Kedvezmeny(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1),
    szorzo BINARY_FLOAT NOT NULL,
    nev VARCHAR2(50) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE Jegy(
    uuid VARCHAR2(36) NOT NULL,
    utas_neve VARCHAR2(100) NOT NULL,
    kocsiosztaly VARCHAR2(50) NOT NULL,
    jaratszam NUMBER NOT NULL,
    kedvezmeny NUMBER NOT NULL,
    PRIMARY KEY(uuid),
    FOREIGN KEY(kocsiosztaly) REFERENCES Arkategoria(cimke),
    FOREIGN KEY(jaratszam) REFERENCES Jarat(jaratszam),
    FOREIGN KEY(kedvezmeny) REFERENCES Kedvezmeny(id)
);
